---
- name: play level varaibles
  hosts: local
  connection: local
  vars:
    COURSE: Devops with AWS  ### Course=ansible,shell we refer $VAR or ${var}
    DURaTION: 10HR
    TRAINER: Satyam

  tasks:
  - name: print course information
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
        msg: "Hello {{ COURSE }}, Course Duration: {{ DURaTION }}, Trainer is {{ TRAINER }}"
